# -*- coding: utf-8 -*-
"""detecção-anomalias-dio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkIb6hTHgHQczpdE11I87kS8-jxGTV9m
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from xgboost import XGBClassifier

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score,
    precision_recall_curve,
    average_precision_score
)

import shap

"""Dataset

"""

url = "https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"

df = pd.read_csv(url)

print("Dimensões:", df.shape)

df.head()

print(df.info())

print(df.describe())

"""Pre-Processamento"""

df["amount_log"] = np.log1p(df["Amount"])

X = df.drop("Class", axis=1)
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

"""Regressão Logística



"""

logistic = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

logistic.fit(
    X_train,
    y_train
)